version: '3.8'
services:
  web:
    image: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${TAG}
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker