version: '3'
services:
  web:
    image: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${TAG}
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == $WORKER_NODE_ROLE]